package model;



// default package
// Generated 13-mar-2019 19:13:41 by Hibernate Tools 5.3.6.Final

/**
 * Catalogos generated by hbm2java
 */
public class Catalogo implements java.io.Serializable {

	private int idCatalogos;
	private String nombre;

	public Catalogo() {
	}

	public Catalogo(int idCatalogos, String nombre) {
		this.idCatalogos = idCatalogos;
		this.nombre = nombre;
	}

	public int getIdCatalogos() {
		return this.idCatalogos;
	}

	public void setIdCatalogos(int idCatalogos) {
		this.idCatalogos = idCatalogos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
