package model;

// default package
// Generated 13-mar-2019 19:13:41 by Hibernate Tools 5.3.6.Final

import java.util.Date;

/**
 * Movimientos generated by hbm2java
 */
public class Movimiento implements java.io.Serializable {

	private int idMovimientos;
	private int idCatalogo;
	private Date fecha;
	private int cantidad;
	private String idCuenta;
	private String tipo;

	public Movimiento() {
	}

	public Movimiento(int idMovimientos, int idCatalogo, Date fecha, int cantidad, String idCuenta, String tipo) {
		this.idMovimientos = idMovimientos;
		this.idCatalogo = idCatalogo;
		this.fecha = fecha;
		this.cantidad = cantidad;
		this.idCuenta = idCuenta;
		this.tipo = tipo;
	}

	public int getIdMovimientos() {
		return this.idMovimientos;
	}

	public void setIdMovimientos(int idMovimientos) {
		this.idMovimientos = idMovimientos;
	}

	public int getIdCatalogo() {
		return this.idCatalogo;
	}

	public void setIdCatalogo(int idCatalogo) {
		this.idCatalogo = idCatalogo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public String getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(String idCuenta) {
		this.idCuenta = idCuenta;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
